import { useEffect, useState } from 'react';
import { PlayerController } from './controllers/PlayerController';
import { Player } from './models/Player';
import { PlayerCard } from './views/components/PlayerCard';
import { ScoutForm } from './views/components/ScoutForm';
import { PlayerModal } from './views/components/PlayerModal'; 
import React from 'react';

function App() {
  const [leaderboard, setLeaderboard] = useState<Player[]>([]);
  const [loading, setLoading] = useState(true);
  const [selectedPlayer, setSelectedPlayer] = useState<Player | null>(null);

  const loadData = async () => {
    setLoading(true);
    const data = await PlayerController.getLeaderboard();
    setLeaderboard(data);
    setLoading(false);
  };

  useEffect(() => {
    loadData();
  }, []);

  return (
    <div style={{ minHeight: '100vh', backgroundColor: '#f8fafc', padding: '2rem 1rem', fontFamily: 'system-ui, sans-serif' }}>
      
      <div style={{ maxWidth: '850px', margin: '0 auto', backgroundColor: '#ffffff', padding: '2.5rem', borderRadius: '16px', boxShadow: '0 10px 25px -5px rgba(0, 0, 0, 0.05)' }}>
        
        <h1 style={{ textAlign: 'center', fontSize: '2.5rem', color: '#0f172a', marginTop: 0 }}>
          ScoutMarket Dashboard
        </h1>
        
        <div style={{ backgroundColor: '#f0fdf4', padding: '1.5rem', borderRadius: '8px', borderLeft: '4px solid #22c55e', marginBottom: '2.5rem' }}>
          <h4 style={{ margin: '0 0 0.5rem 0', color: '#0f172a' }}>📊 Algorithm Methodology</h4>
          <p style={{ margin: 0, fontSize: '0.95rem', color: '#475569', lineHeight: '1.6' }}>
              ScoutMarket evaluates players using a weighted production index. We provide a <strong>Baseline Valuation</strong> calculated as: <code>€10M + (Goals × €5M) + (Assists × €3M)</code>. We then apply an <strong>Age Multiplier</strong> (20% bonus for U23s) to determine true market worth. The <strong>ROI Score</strong> is generated by comparing our AI evaluation against your custom offer price.
          </p>
        </div>

        <ScoutForm onScoutSuccess={loadData} />

        <h2 style={{ color: '#334155', borderBottom: '2px solid #e2e8f0', paddingBottom: '0.5rem', marginTop: '2.5rem' }}>
          Live Top Valuations
        </h2>

        {loading ? (
            <div style={{ textAlign: 'center', padding: '2rem', color: '#64748b' }}>
                <p style={{ fontSize: '1.2rem', fontWeight: '500' }}>Syncing with Java Server...</p>
            </div>
        ) : (
          leaderboard.map((player, index) => (
            <PlayerCard 
              key={player.playerID} 
              player={player} 
              rank={index + 1}
              onClick={() => setSelectedPlayer(player)} 
            />
          ))
        )}

        {selectedPlayer && (
          <PlayerModal 
            player={selectedPlayer} 
            onClose={() => setSelectedPlayer(null)} 
          />
        )}
      </div>
    </div>
  );
}

export default App;